### PR TITLE
Create fixed_bids

### PR DESCRIPTION
**Pull request by phypsie**
@chilicrab @sunnyflight @phypsie @yohong16 @kmss21

### CODE REVIEW

**Comment by kmss21** [comment]
Good! I think we should reflect some flexibility and documentation principle when proceeding a project. 
@phypsie

**Comment by yohong16** [comment]
Good job Phillip! You talked about solving problems as they emerge in just-in-time fashion and I do remember the professor explaining about Kanban by David Anderson on limiting work-in-progress and minimizing cycle time.
It'll be even better if there is an example of an exception when it is OK to have a fixed bid.
Other than that, it's :+1: to go!
@phypsie

**Comment by sunnyflight** [comment]
Agree with you with the advantages of iterative software development. But it is true that with budget and time constraints a reality in today's corporate world, many managers opt for the fixed bid method because they feel that fixed bids allow them to have more control over the actual expenses. In the end, some managers are content with just having something developed rather than being concerned with the quality of the developed program.

**Comment by chilicrab** [comment]
Excellent job Phillip!!
I have a experience working with some engineers developing trading back office system and we actually made a fixed bid contract. However, our term included free one month warranty period. So without paying extra fee, they'll come and see or remotely fix the problem. That way, maybe we can offset the problem with fixed bid.
I think it's :+1: to ship!!

**Pull request merged**
